### ISSUE TITLE
Grid column styles doesn't applying

### ISSUE THREAD

**Issue by r72cccp** [react-mdl/react-mdl#455]
I'm looking at result - classes `mdl-cell--12-col-phone mdl-cell--6-col-tablet` not applying and not loading.
In `extra/material-grid.css` and `extra/material.css` i'd find strange class definitions:

![first explanation of trouble - classes col-8, col-12 not applying](https://github.com/r72cccp/assets/blob/master/img/Trouble_1%20-%20col-12%20not%20apply.png?raw=true)

```css
  .mdl-cell--12-col,
  .mdl-cell--12-col-phone.mdl-cell--12-col-phone {
    width: calc(100% - 16px); }
    .mdl-grid--no-spacing > .mdl-cell--12-col, .mdl-grid--no-spacing >
    .mdl-cell--12-col-phone.mdl-cell--12-col-phone {
      width: 100%; }
```

the problem hide in, i'm think, in strange class concatenation:

![strange classes concatenation](https://github.com/r72cccp/assets/blob/master/img/Trouble_1%20-%20col-12%20not%20apply%20-%20styles.png?raw=true)
